version: "3"

services:
  # In development, open ES port so host API can connect to it
  elasticsearch:
    ports:
      - 9200:9200

  python:
    volumes:
      - ./packages/code-du-travail-data/:/app

  nlp_api:
    environment:
      - FLASK_RUN_PORT=$NLP_PORT
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./packages/code-du-travail-nlp/:/app

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
