version: "3"

services:
  # In production, dockerize the frontend
  frontend:
    image: socialgouv/code-du-travail-numerique-frontend:latest
    restart: always
    env_file:
      - .env
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT

  # In production, dockerize the API
  api:
    image: socialgouv/code-du-travail-numerique-api:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - elasticsearch
    environment:
      # defaults for production
      - APM_SERVER_URL=http://apm:8200
      - APM_SERVER_ACTIVE=1
      - $API_DOCS_DIR=$API_DOCS_DIR
    ports:
      - $API_PORT:$API_PORT

  # In production, add an APM Server
  apm:
    image: docker.elastic.co/apm/apm-server:6.4.2
    depends_on:
      - elasticsearch
    environment:
      - logging.level=trace
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=elasticsearch:9200
      - output.elasticsearch.enabled=true

  # In production, add kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
