version: "3"

services:
  # In production, use registry image
  elasticsearch:
    restart: always
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/elasticsearch:$CDTN_HASH
    ports:
      - 9200:9200

  frontend:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/frontend:$CDTN_HASH
    restart: always
    env_file:
      - .env
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT

  api:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/api:$CDTN_HASH
    restart: always
    env_file:
      - .env
    depends_on:
      - elasticsearch
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./packages/code-du-travail-data/dataset/courrier-type/docx:/code-du-travail-data/dataset/courrier-type/docx

  nlp_api:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/nlp:$CDTN_HASH
    restart: always
    environment:
      - FLASK_ENV=production

  data:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/data:$CDTN_HASH
