variables:
  APM_SERVER_PORT: 8200
  DOCKER_COMPOSE_VERSION: "1.23.2"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_VERSION: 18
  ELASTICSEARCH_INTER_NODE_PORT: 9300
  ELASTICSEARCH_PORT: 9200
  ELK_STACK_VERSION: 7.3.1
  FRONTEND_PORT: 3000
  GIT_STRATEGY: fetch
  HASH_SIZE: 7
  IMAGE_INFRA_BASE_NAME: infra/images-docker
  KIBANA_PORT: 5601
  NLP_PORT: 5000
  PYTHON_VERSION: 3.7.2-alpine
  SUGGEST_DATA_URL: "https://gist.githubusercontent.com/ArmandGiraud/aaa65ed694e6b8d46918d44e41bae9e4/raw/2b5fa5ff67d87bbf08b33fecfe2fb98e15c73a06/data-test.txt"
