---
kind: Service
apiVersion: v1
metadata:
  name: cdtn-frontend${HASH_BRANCH_NAME}
  labels:
    app: cdtn-frontend${HASH_BRANCH_NAME}
    branch: ${BRANCH_NAME}
    commit: ${COMMIT}
    job: "${JOB_ID}"
spec:
  selector:
    app: cdtn-frontend${HASH_BRANCH_NAME}
  ports:
  - port: ${PORT}
    name: frontend
