cluster.name: "code-du-travail-data-elasticsearch"
node.name: "code-du-travail-data-elasticsearch-single-node"
network.host: 0.0.0.0

# Use single node discovery in order for the node to elect itself master and not join a cluster with any other node.
# https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
discovery.type: single-node

# https://github.com/mobz/elasticsearch-head#enable-cors-in-elasticsearch
http.cors.enabled: true
http.cors.allow-origin: "*"

xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false
