#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_create_namespace_stage.yml
    ref: v9.1.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_nodejs_chart_stage.yml
    ref: v9.1.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_hpa_chart_stage.yml
    ref: v9.1.1

#

Create namespace:
  extends:
    - .base_create_namespace_stage
    - .dev_stage
  stage: "Post Registration"
  before_script:
    - source ./.gitlab-ci/env.sh
  after_script:
    - source ./.gitlab-ci/env.sh
    #
    # Create cdtn secrets
    - envsubst < ./.k8s/secrets.yml | kubectl apply -n ${K8S_NAMESPACE} -f - || true
    #
    # Copy elasticsearch-creds
    - kubectl get secret elasticsearch-cloud-data --namespace=cdtn-secret --export -o yaml |
      kubectl apply --namespace=${K8S_NAMESPACE} -f -
    - kubectl get secret elasticsearch-cloud-api --namespace=cdtn-secret --export -o yaml |
      kubectl apply --namespace=${K8S_NAMESPACE} -f -
    - kubectl get secret elastic-apm --namespace=cdtn-secret --export -o yaml |
      kubectl apply --namespace=${K8S_NAMESPACE} -f -
#

.deploy_stage: &deploy_stage
  stage: "Deploy"
  dependencies: []
  except:
    variables:
      # Don't run when running e2e tests
      - $E2E_TEST
  services:
    - docker:dind
  variables: &deploy_stage_variables
    IMAGE_TAG: ${CI_COMMIT_SHA}
    REGISTRY: ${CI_REGISTRY_IMAGE}

.prod_stage: &prod_stage
  environment:
    name: prod
  only:
    variables:
      - $PRODUCTION

#

.dev_stage: &dev_stage
  environment:
    name: fabrique-dev
  except:
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't run when running e2e tests
      - $E2E_TEST
      # Don't register a base image for release commit
      # that only bump version / udpate changelog
      - $CI_COMMIT_MESSAGE =~ /^chore(release):*/
#
#
#

.deploy_api_stage: &deploy_api_stage
  <<: *deploy_stage
  extends: .base_deploy_hpa_chart_stage
  variables:
    <<: *deploy_stage_variables
    CONTEXT: api
    PORT: 8000
    VALUES_FILE: ./.k8s/api.values.yml
    ENABLE_APM: "false"
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${API_HOST}

#

Deploy @cdtn/api (dev):
  extends:
    - .deploy_api_stage
    - .dev_stage
  dependencies:
    - Register nlp image
  variables:
    HELM_RENDER_ARGS: >-
      --set autoscaling.enabled=false
      --set deployment.resources.requests.memory=256Mi
      --set deployment.resources.requests.cpu=.3m

Deploy @cdtn/api (prod):
  extends:
    - .deploy_api_stage
    - .prod_stage
  variables:
    ENABLE_APM: "true"
#
#
#

.deploy_frontend_stage: &deploy_frontend_stage
  <<: *deploy_stage
  extends: .base_deploy_hpa_chart_stage
  variables:
    <<: *deploy_stage_variables
    PORT: ${FRONTEND_PORT}
    CONTEXT: frontend
    VALUES_FILE: ./.k8s/frontend.values.yml
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${FRONTEND_HOST}

#

Deploy @cdtn/frontend (dev):
  extends:
    - .deploy_frontend_stage
    - .dev_stage
  dependencies:
    - Register nlp image
  variables:
    HELM_RENDER_ARGS: >-
      --set autoscaling.enabled=false
      --set deployment.resources.requests.memory=256Mi
      --set deployment.resources.requests.cpu=.1m
  artifacts:
    expire_in: 30 mins
    paths:
      - packages/code-du-travail-nlp

Deploy @cdtn/frontend (prod):
  <<: *deploy_frontend_stage
  <<: *prod_stage

Deploy @cdtn/frontend extra ingress(prod):
  <<: *deploy_stage
  <<: *prod_stage
  extends: .base_docker_kubectl_image_stage
  script:
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - cat ./.k8s/ingress-prod.yml | envsubst | kubectl apply -f -
  before_script:
    - source ./.gitlab-ci/env.sh

#
#
#

.deploy-data: &deploy_data
  <<: *deploy_stage
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/kubectl:0.20.0
  dependencies: []
  variables:
    <<: *deploy_stage_variables
    CONTEXT: data
    ES_PORT: ${ELASTICSEARCH_PORT}
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/data
  script:
    - source ./.gitlab-ci/env.sh
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    #
    - kubectl delete job ${CONTEXT} || true
    - cat ./.k8s/data.job.yml | envsubst | kubectl apply -f -

#

Update Elasticsearch Index (manual):
  extends:
      - .deploy-data
  environment:
    name: prod
  only:
    refs:
      - master
  when: manual
  variables:
    PRODUCTION: "true"

Create Elasticsearch Index (dev):
  <<: *deploy_data
  <<: *dev_stage

Create Elasticsearch Index (prod):
  <<: *deploy_data
  <<: *prod_stage

#
#
#

.deploy_nlp_stage: &deploy_nlp_stage
  <<: *deploy_stage
  extends: .base_deploy_nodejs_chart_stage
  variables:
    <<: *deploy_stage_variables
    PORT: ${NLP_PORT}
    CONTEXT: nlp
    VALUES_FILE: ./.k8s/nlp.values.yml
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${NLP_HOST}
    #
    - >-
      if [[ "${BRANCH_NAME}" != "master" ]] && [[ "${HOST}" == *"master"* ]]; then
        exit "${CI_JOB_SKIP_EXIT_CODE:-0}"
      fi
  artifacts:
    expire_in: 30 mins
    paths:
      - packages/code-du-travail-${CONTEXT}
#

Deploy @cdtn/nlp (dev):
  extends:
    - .deploy_nlp_stage
    - .dev_stage
  dependencies:
    - Register nlp image
  variables:
    HELM_RENDER_ARGS: >-
      --set deployment.resources.requests.memory=1Gi
      --set deployment.resources.requests.cpu=5m

Deploy @cdtn/nlp (prod):
  <<: *deploy_nlp_stage
  <<: *prod_stage
