#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_create_namespace_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_nodejs_chart_stage.yml
    ref: v9.1.2
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_hpa_chart_stage.yml
    ref: v9.1.2


#

Create namespace:
  extends:
    - .base_create_namespace_stage
    - .dev_stage
  environment:
    name: ${CI_COMMIT_REF_SLUG}-dev2
  stage: "Registration"
  before_script:
    - source ./.gitlab-ci/env.sh
  after_script:
    - source ./.gitlab-ci/env.sh
    #
    # Create cdtn secrets
    - envsubst < ./.k8s/secrets.yml | kubectl apply -n ${K8S_NAMESPACE} -f - || true
    #
    # Copy elasticsearch-creds
    - kubectl get secret elasticsearch-cloud-data --namespace=cdtn-secret --export -o yaml |
      kubectl apply --namespace=${K8S_NAMESPACE} -f -
    - kubectl get secret elasticsearch-cloud-api --namespace=cdtn-secret --export -o yaml |
      kubectl apply --namespace=${K8S_NAMESPACE} -f -
    - kubectl get secret elastic-apm --namespace=cdtn-secret --export -o yaml |
      kubectl apply --namespace=${K8S_NAMESPACE} -f -
#

.deploy_stage: &deploy_stage
  stage: "Deploy"
  dependencies: []
  services:
    - docker:dind
  variables: &deploy_stage_variables
    IMAGE_TAG: ${CI_COMMIT_SHA}
    REGISTRY: ${CI_REGISTRY_IMAGE}

.prod_stage: &prod_stage
  environment:
    name: prod2
  only:
    variables:
      - $PRODUCTION
  except:
    variables:
    # Don't run when updating Elasticloud data
    - $UPDATE_ES_INDEX

#

.dev_stage: &dev_stage
  environment:
    name: ${CI_COMMIT_REF_SLUG}-dev2
  except:
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't run when updating Elasticloud data
      - $UPDATE_ES_INDEX
      # Don't register a base image for release commit
      # that only bump version / udpate changelog
      - $CI_COMMIT_MESSAGE =~ /^chore(release):*/

#
#

.deploy_frontend_stage: &deploy_frontend_stage
  <<: *deploy_stage
  extends: .base_deploy_hpa_chart_stage
  variables:
    <<: *deploy_stage_variables
    PORT: ${FRONTEND_PORT}
    CONTEXT: frontend
    VALUES_FILE: ./.k8s/frontend.values.yml
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${FRONTEND_HOST}

#

Deploy @cdtn/frontend (dev):
  extends:
    - .deploy_frontend_stage
    - .dev_stage
  variables:
    HELM_RENDER_ARGS: >-
      --set autoscaling.enabled=false
      --set deployment.resources.requests.memory=256Mi
      --set deployment.resources.requests.cpu=.1m
      --set ingress.annotations.certmanager\.k8s\.io/cluster-issuer=null
      --set ingress.annotations.kubernetes\.io/tls-acme=null

Deploy @cdtn/frontend (prod):
  <<: *deploy_frontend_stage
  <<: *prod_stage

Deploy @cdtn/frontend extra ingress(prod):
  <<: *deploy_stage
  <<: *prod_stage
  extends: .base_docker_kubectl_image_stage
  script:
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - cat ./.k8s/ingress-prod.yml | envsubst | kubectl apply -f -
  before_script:
    - source ./.gitlab-ci/env.sh

#
#
#

.deploy-data: &deploy_data
  <<: *deploy_stage
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/kubectl:0.20.0
  variables:
    <<: *deploy_stage_variables
    CONTEXT: data
    ES_PORT: ${ELASTICSEARCH_PORT}
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/data
  script:
    - source ./.gitlab-ci/env.sh
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    #
    - kubectl delete job ${CONTEXT} || true
    - cat ./.k8s/data.job.yml | envsubst | kubectl apply -f -

#
# Temporary disabled
# Update Elasticsearch Index:
#   extends:
#     - .deploy-data
#   stage: "Update ES data"
#   environment:
#     name: prod2
#   only:
#     refs:
#       - master
#     variables:
#       - $CI_COMMIT_MESSAGE =~ /update @socialgouv data packages/
#   variables:
#     PRODUCTION: "true"

Create Elasticsearch Index (dev):
  <<: *deploy_data
  <<: *dev_stage

Create Elasticsearch Index (prod):
  <<: *deploy_data
  <<: *prod_stage
