#
#
#

Release:
  stage: .post
  image: node:14.17-alpine3.13
  dependencies: []
  when: manual
  variables:
    LERNA_ARGS: --force-publish --yes --conventional-commits
  except:
    refs:
      # Don't tag tags
      - tags
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
  before_script:
    - npm config set access public
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - apk add --no-cache git=~2
    - git checkout ${CI_COMMIT_REF_SLUG}
    - git config user.name "${CI_GIT_AUTHOR_NAME}"
    - git config user.email "${CI_GIT_AUTHOR_EMAIL}"
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${PROJECT_PATH}.git
    - yarn --frozen-lockfile
    - yarn build:npm
  script:
    - GH_TOKEN=${GITHUB_TOKEN} yarn lerna version ${LERNA_ARGS:="--force-publish --yes"}
    - yarn lerna publish from-package --yes

#
#
#

Production:
  stage: .post
  image: curlimages/curl:7.67.0
  dependencies: []
  when: manual
  only:
    refs:
      - tags
  except:
    variables:
      # Don't run when deploying in production an existing image
      - $PRODUCTION
      # Don't register a base image for release commit
      # that only bump version / udpate changelog
      - $CI_COMMIT_MESSAGE =~ /^chore(release):*/
  script:
    - echo "deploy ${CI_COMMIT_TAG}"
    - curl --request POST
      --form ref="${CI_COMMIT_TAG}"
      --form token="${CI_JOB_TOKEN}"
      --form variables[PRODUCTION]="true"
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/trigger/pipeline
