#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_notify_github_stage.yml
    ref: v9.1.1
  - project: SocialGouv/gitlab-ci-yml
    file: /base_delete_useless_k8s_ns_stage.yml
    ref: v9.1.1

#

.notify_stage: &notify_stage
  except:
    variables:
      # Don't run when running e2e tests
      - $E2E_TEST

#

Notify Starting Deployment:
  <<: *notify_stage
  extends: .base_notify_pending_stage
  stage: Deploy

Notify Fail:
  <<: *notify_stage
  extends: .base_notify_fail_stage
  stage: Notify Finished Deployment
  dependencies:
    - Notify Starting Deployment
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${FRONTEND_URL}

Notify Success:
  <<: *notify_stage
  extends: .base_notify_success_stage
  stage: Notify Finished Deployment
  dependencies:
    - Notify Starting Deployment
  before_script:
    - source ./.gitlab-ci/env.sh
    - HOST=${FRONTEND_URL}

Delete useless k8s namespaces:
  <<: *notify_stage
  environment: fabrique-tmp
  extends: .base_delete_useless_k8s_ns_stage
