#

.prepare_stage: &prepare_stage
  extends: .base-docker-image-stage
  stage: "Prepare"
  dependencies: []
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
    # NOTE(douglasduteil): do not fail if no previous sha image exist
    - docker pull $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA || true
  script:
    - echo "Build $IMAGE_NAME:$CI_COMMIT_SHA from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA"
    - docker build --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA -t $IMAGE_NAME:$CI_COMMIT_SHA $CONTEXT
    - docker push $IMAGE_NAME

#

Register socialgouv/cdtn base image:
  <<: *prepare_stage
  variables:
    CONTEXT: .
    IMAGE_NAME: $CI_REGISTRY_IMAGE

Register elasticsearch image:
  extends: .base-docker-image-stage
  stage: "Prepare"
  dependencies: []
  before_script:
  - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
  # NOTE(douglasduteil): do not fail if no previous sha image exist
  - docker pull $IMAGE_NAME:$ELK_STACK_VERSION || true
  script:
  - echo "Build $IMAGE_NAME:$ELK_STACK_VERSION from $IMAGE_NAME:$ELK_STACK_VERSION"
  - docker build --cache-from $IMAGE_NAME:$ELK_STACK_VERSION -t $IMAGE_NAME:$ELK_STACK_VERSION --file $DOCKERFILE $CONTEXT
  - docker push $IMAGE_NAME
variables:
  CONTEXT: packages/code-du-travail-data
  DOCKERFILE: packages/code-du-travail-data/elasticsearch.Dockerfile
  IMAGE_NAME: $CI_REGISTRY_IMAGE/elasticsearch
