---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana${BRANCH_NAME}
  labels:
    app: kibana${BRANCH_NAME}
    branch: cdtn${BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana${BRANCH_NAME}
  template:
    metadata:
      labels:
        app: kibana${BRANCH_NAME}
    spec:
      containers:
      - name: kibana${BRANCH_NAME}
        image: docker.elastic.co/kibana/kibana:6.4.2
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch${BRANCH_NAME}:9200
        ports:
        - containerPort: 5601
