kind: ConfigMap
apiVersion: v1
metadata:
  name: www-configmap
data:
  ELASTIC_APM_ACTIVE: "false"
  ELASTIC_APM_SERVICE_NAME: "cdtn-api"
  ELASTIC_APM_USE_PATH_AS_TRANSACTION_NAME: "true"
  NLP_URL: "https://serving-ml.fabrique.social.gouv.fr"
  NODE_ENV: "production"
  PIWIK_SITE_ID: "3"
  PIWIK_URL: "https://matomo.fabrique.social.gouv.fr"
