---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cdtn-frontend${BRANCH_NAME}
  labels:
    app: cdtn-frontend${BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdtn-frontend${BRANCH_NAME}
  template:
    metadata:
      labels:
        app: cdtn-frontend${BRANCH_NAME}
    spec:
      containers:
      - image:  registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/frontend:${IMAGE_TAG}
        name: cdtn-frontend
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          value: http://code-du-travail-numerique-api${BRANCH_NAME}.ops.factory.social.gouv.fr/api/v1
