---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cdtn-frontend${HASH_BRANCH_NAME}
  labels:
    app: cdtn-frontend${HASH_BRANCH_NAME}
    branch: cdtn${HASH_BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdtn-frontend${HASH_BRANCH_NAME}
  template:
    metadata:
      labels:
        app: cdtn-frontend${HASH_BRANCH_NAME}
    spec:
      containers:
      - image:  ${CDTN_REGISTRY}/frontend:${IMAGE_TAG}
        name: cdtn-frontend
        ports:
        - containerPort: ${PORT}
        livenessProbe:
          httpGet:
            path: /
            port: ${PORT}
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: ${PORT}
          initialDelaySeconds: 3
          periodSeconds: 5
        env:
        - name: API_URL
          value: http://code-du-travail-numerique-api${HASH_BRANCH_NAME}.${ENVIRONMENT}.factory.social.gouv.fr/api/v1
